// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    3DCharts: typeof import('./src/components/3DCharts.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    DisabledIcon: typeof import('./src/components/icons/DisabledIcon.vue')['default']
    Graphs: typeof import('./src/components/Graphs.vue')['default']
    GridCards: typeof import('./src/components/GridCards.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTable: typeof import('naive-ui')['NTable']
    NTooltip: typeof import('naive-ui')['NTooltip']
    SearchTab: typeof import('./src/components/SearchTab.vue')['default']
  }
}

export { }
